---
- name: Install Docker
  apk:
    name:
      - docker
      - docker-cli
      - docker-compose
      - docker-cli-compose
    state: present

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Get remote username for docker group
  become: no
  command: whoami
  register: docker_remote_user
  changed_when: false

- name: Add user to docker group
  user:
    name: "{{ docker_remote_user.stdout }}"
    groups: docker
    append: yes

- name: Add Docker service to boot
  command: rc-update add docker boot
  changed_when: false
  ignore_errors: yes

- name: Start Docker service
  service:
    name: docker
    state: started
